export type City = {
  slug: string;
  name: string;            // Москва
  nameIn: string;          // в Москву
  nameFrom: string;        // из Москвы
  nameLocative: string;    // в Москве
  deliveryDays: string;    // срок доставки авто
  deliveryDaysAvia: string;// срок доставки авиа
  pvz: string;             // ближайший ПВЗ / способ получения
  population?: string;
};

export const CITIES: City[] = [
  {
    slug: 'moskva',
    name: 'Москва',
    nameIn: 'в Москву',
    nameFrom: 'из Москвы',
    nameLocative: 'в Москве',
    deliveryDays: '12–18 дней',
    deliveryDaysAvia: '7–10 дней',
    pvz: 'СДЭК / Boxberry / 5Post — более 2000 пунктов',
    population: '13 млн',
  },
  {
    slug: 'sankt-peterburg',
    name: 'Санкт-Петербург',
    nameIn: 'в Санкт-Петербург',
    nameFrom: 'из Санкт-Петербурга',
    nameLocative: 'в Санкт-Петербурге',
    deliveryDays: '14–20 дней',
    deliveryDaysAvia: '8–11 дней',
    pvz: 'СДЭК / Boxberry / 5Post — более 1500 пунктов',
    population: '5,6 млн',
  },
  {
    slug: 'ekaterinburg',
    name: 'Екатеринбург',
    nameIn: 'в Екатеринбург',
    nameFrom: 'из Екатеринбурга',
    nameLocative: 'в Екатеринбурге',
    deliveryDays: '14–20 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 400 пунктов',
    population: '1,5 млн',
  },
  {
    slug: 'novosibirsk',
    name: 'Новосибирск',
    nameIn: 'в Новосибирск',
    nameFrom: 'из Новосибирска',
    nameLocative: 'в Новосибирске',
    deliveryDays: '12–17 дней',
    deliveryDaysAvia: '8–11 дней',
    pvz: 'СДЭК / Boxberry — более 350 пунктов',
    population: '1,6 млн',
  },
  {
    slug: 'kazan',
    name: 'Казань',
    nameIn: 'в Казань',
    nameFrom: 'из Казани',
    nameLocative: 'в Казани',
    deliveryDays: '14–19 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 300 пунктов',
    population: '1,3 млн',
  },
  {
    slug: 'nizhniy-novgorod',
    name: 'Нижний Новгород',
    nameIn: 'в Нижний Новгород',
    nameFrom: 'из Нижнего Новгорода',
    nameLocative: 'в Нижнем Новгороде',
    deliveryDays: '14–19 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 250 пунктов',
    population: '1,2 млн',
  },
  {
    slug: 'krasnodar',
    name: 'Краснодар',
    nameIn: 'в Краснодар',
    nameFrom: 'из Краснодара',
    nameLocative: 'в Краснодаре',
    deliveryDays: '15–21 день',
    deliveryDaysAvia: '10–13 дней',
    pvz: 'СДЭК / Boxberry — более 250 пунктов',
    population: '1 млн',
  },
  {
    slug: 'rostov-na-donu',
    name: 'Ростов-на-Дону',
    nameIn: 'в Ростов-на-Дону',
    nameFrom: 'из Ростова-на-Дону',
    nameLocative: 'в Ростове-на-Дону',
    deliveryDays: '15–21 день',
    deliveryDaysAvia: '10–13 дней',
    pvz: 'СДЭК / Boxberry — более 220 пунктов',
    population: '1,1 млн',
  },
  {
    slug: 'samara',
    name: 'Самара',
    nameIn: 'в Самару',
    nameFrom: 'из Самары',
    nameLocative: 'в Самаре',
    deliveryDays: '14–19 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 200 пунктов',
    population: '1,1 млн',
  },
  {
    slug: 'ufa',
    name: 'Уфа',
    nameIn: 'в Уфу',
    nameFrom: 'из Уфы',
    nameLocative: 'в Уфе',
    deliveryDays: '14–19 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 180 пунктов',
    population: '1,1 млн',
  },
  {
    slug: 'chelyabinsk',
    name: 'Челябинск',
    nameIn: 'в Челябинск',
    nameFrom: 'из Челябинска',
    nameLocative: 'в Челябинске',
    deliveryDays: '14–19 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 200 пунктов',
    population: '1,2 млн',
  },
  {
    slug: 'krasnoyarsk',
    name: 'Красноярск',
    nameIn: 'в Красноярск',
    nameFrom: 'из Красноярска',
    nameLocative: 'в Красноярске',
    deliveryDays: '13–18 дней',
    deliveryDaysAvia: '8–11 дней',
    pvz: 'СДЭК / Boxberry — более 180 пунктов',
    population: '1,1 млн',
  },
  {
    slug: 'voronezh',
    name: 'Воронеж',
    nameIn: 'в Воронеж',
    nameFrom: 'из Воронежа',
    nameLocative: 'в Воронеже',
    deliveryDays: '14–20 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 180 пунктов',
    population: '1 млн',
  },
  {
    slug: 'volgograd',
    name: 'Волгоград',
    nameIn: 'в Волгоград',
    nameFrom: 'из Волгограда',
    nameLocative: 'в Волгограде',
    deliveryDays: '15–20 дней',
    deliveryDaysAvia: '10–13 дней',
    pvz: 'СДЭК / Boxberry — более 160 пунктов',
    population: '1 млн',
  },
  {
    slug: 'perm',
    name: 'Пермь',
    nameIn: 'в Пермь',
    nameFrom: 'из Перми',
    nameLocative: 'в Перми',
    deliveryDays: '14–19 дней',
    deliveryDaysAvia: '9–12 дней',
    pvz: 'СДЭК / Boxberry — более 170 пунктов',
    population: '1 млн',
  },
  {
    slug: 'vladivostok',
    name: 'Владивосток',
    nameIn: 'во Владивосток',
    nameFrom: 'из Владивостока',
    nameLocative: 'во Владивостоке',
    deliveryDays: '7–12 дней',
    deliveryDaysAvia: '5–8 дней',
    pvz: 'СДЭК / Boxberry — более 100 пунктов',
    population: '600 тыс.',
  },
  {
    slug: 'irkutsk',
    name: 'Иркутск',
    nameIn: 'в Иркутск',
    nameFrom: 'из Иркутска',
    nameLocative: 'в Иркутске',
    deliveryDays: '11–16 дней',
    deliveryDaysAvia: '7–10 дней',
    pvz: 'СДЭК / Boxberry — более 120 пунктов',
    population: '600 тыс.',
  },
  {
    slug: 'tyumen',
    name: 'Тюмень',
    nameIn: 'в Тюмень',
    nameFrom: 'из Тюмени',
    nameLocative: 'в Тюмени',
    deliveryDays: '13–18 дней',
    deliveryDaysAvia: '8–11 дней',
    pvz: 'СДЭК / Boxberry — более 140 пунктов',
    population: '850 тыс.',
  },
  {
    slug: 'omsk',
    name: 'Омск',
    nameIn: 'в Омск',
    nameFrom: 'из Омска',
    nameLocative: 'в Омске',
    deliveryDays: '13–18 дней',
    deliveryDaysAvia: '8–11 дней',
    pvz: 'СДЭК / Boxberry — более 150 пунктов',
    population: '1,1 млн',
  },
  {
    slug: 'saratov',
    name: 'Саратов',
    nameIn: 'в Саратов',
    nameFrom: 'из Саратова',
    nameLocative: 'в Саратове',
    deliveryDays: '15–20 дней',
    deliveryDaysAvia: '10–13 дней',
    pvz: 'СДЭК / Boxberry — более 140 пунктов',
    population: '830 тыс.',
  },
  {
    slug: 'tolyatti',
    name: 'Тольятти',
    nameIn: 'в Тольятти',
    nameFrom: 'из Тольятти',
    nameLocative: 'в Тольятти',
    deliveryDays: '15–20 дней',
    deliveryDaysAvia: '10–13 дней',
    pvz: 'СДЭК / Boxberry — более 110 пунктов',
    population: '690 тыс.',
  },
  {
    slug: 'kaliningrad',
    name: 'Калининград',
    nameIn: 'в Калининград',
    nameFrom: 'из Калининграда',
    nameLocative: 'в Калининграде',
    deliveryDays: '18–25 дней',
    deliveryDaysAvia: '12–15 дней',
    pvz: 'СДЭК / Boxberry — более 90 пунктов',
    population: '500 тыс.',
  },
  {
    slug: 'sochi',
    name: 'Сочи',
    nameIn: 'в Сочи',
    nameFrom: 'из Сочи',
    nameLocative: 'в Сочи',
    deliveryDays: '16–22 дня',
    deliveryDaysAvia: '11–14 дней',
    pvz: 'СДЭК / Boxberry — более 80 пунктов',
    population: '450 тыс.',
  },
  {
    slug: 'habarovsk',
    name: 'Хабаровск',
    nameIn: 'в Хабаровск',
    nameFrom: 'из Хабаровска',
    nameLocative: 'в Хабаровске',
    deliveryDays: '8–13 дней',
    deliveryDaysAvia: '5–8 дней',
    pvz: 'СДЭК / Boxberry — более 100 пунктов',
    population: '600 тыс.',
  },
  {
    slug: 'tomsk',
    name: 'Томск',
    nameIn: 'в Томск',
    nameFrom: 'из Томска',
    nameLocative: 'в Томске',
    deliveryDays: '13–18 дней',
    deliveryDaysAvia: '8–11 дней',
    pvz: 'СДЭК / Boxberry — более 110 пунктов',
    population: '570 тыс.',
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}
